In [154]:
import numpy as np
import pandas as pd
import math
import time
import gym
import matplotlib.pyplot as plt

In [155]:
import pandas as pd

data = pd.DataFrame({'Price Open' : [2,3,4,5,6,10],
                      'Price Close' : [3,4,5,6,10,15]})

data

Price Open  Price Close
0           2            3
1           3            4
2           4            5
3           5            6
4           6           10
5          10           15

In [156]:
class FinRL:

    def __init__(self):
        self.action_space = ['Buy','Hold','Sell']
        self.func = None

    def load_data(self, data):
        self.data = pd.DataFrame(data)
        print("Data Loaded Successfully.")
    
    def build_states(self):
        try:
            open_price = self.data['Price Open']
            close_price = self.data['Price Close']
            movement = close_price - open_price
            return pd.DataFrame({'Price Open' : open_price,
                    'Price Close' : close_price,
                    'Movement' : movement})
        except:
            print("Please use the load_data function to load the data first.")

    def pipeline(self, window_size = 5):
        avg_closing_price = []
        for i in range(0, self.data.shape[0]-window_size):
            avg_closing_price.append(self.data['Price Close'].values[i:i+window_size])

        self.func = avg_closing_price
        return avg_closing_price
    
    def pipeline_avgs(self):
        return np.array(self.func).mean(axis = 1)



In [157]:
test = FinRL()

In [158]:
test.action_space

['Buy', 'Hold', 'Sell']

In [159]:
test.load_data(data)

Data Loaded Successfully.


In [160]:
test.data

Price Open  Price Close
0           2            3
1           3            4
2           4            5
3           5            6
4           6           10
5          10           15

In [161]:
test.build_states()

Price Open  Price Close  Movement
0           2            3         1
1           3            4         1
2           4            5         1
3           5            6         1
4           6           10         4
5          10           15         5

In [162]:
test.pipeline(window_size=2)

[array([3, 4], dtype=int64),
 array([4, 5], dtype=int64),
 array([5, 6], dtype=int64),
 array([ 6, 10], dtype=int64)]

In [163]:
test.pipeline_avgs()

array([3.5, 4.5, 5.5, 8. ])