In [167]:
import numpy as np
import pandas as pd
import math
import time
import gym
import matplotlib.pyplot as plt

In [168]:
import pandas as pd

data = pd.DataFrame({'Price Open' : [2,3,4,5,6,10,15,20,12,11],
                      'Price Close' : [3,4,5,6,10,15,20,12,11,10]})

data

Price Open  Price Close
0           2            3
1           3            4
2           4            5
3           5            6
4           6           10
5          10           15
6          15           20
7          20           12
8          12           11
9          11           10

In [169]:
class FinRL:

    def __init__(self):
        self.action_space = ['Buy','Hold','Sell']
        self.func = None

    def load_data(self, data):
        self.data = pd.DataFrame(data)
        print("Data Loaded Successfully.")
    
    def build_states(self):
        try:
            open_price = self.data['Price Open']
            close_price = self.data['Price Close']
            movement = close_price - open_price
            return pd.DataFrame({'Price Open' : open_price,
                    'Price Close' : close_price,
                    'Movement' : movement})
        except:
            print("Please use the load_data function to load the data first.")

    def pipeline(self, window_size = 5):
        avg_closing_price = []
        for i in range(0, self.data.shape[0]-window_size):
            avg_closing_price.append(self.data['Price Close'].values[i:i+window_size])

        self.func = avg_closing_price
        return avg_closing_price
    
    def pipeline_avgs(self):
        return np.array(self.func).mean(axis = 1)



In [170]:
test = FinRL()

In [171]:
test.action_space

['Buy', 'Hold', 'Sell']

In [172]:
test.load_data(data)

Data Loaded Successfully.


In [173]:
test.data

Price Open  Price Close
0           2            3
1           3            4
2           4            5
3           5            6
4           6           10
5          10           15
6          15           20
7          20           12
8          12           11
9          11           10

In [174]:
test.build_states()

Price Open  Price Close  Movement
0           2            3         1
1           3            4         1
2           4            5         1
3           5            6         1
4           6           10         4
5          10           15         5
6          15           20         5
7          20           12        -8
8          12           11        -1
9          11           10        -1

In [175]:
test.pipeline(window_size=2)

[array([3, 4], dtype=int64),
 array([4, 5], dtype=int64),
 array([5, 6], dtype=int64),
 array([ 6, 10], dtype=int64),
 array([10, 15], dtype=int64),
 array([15, 20], dtype=int64),
 array([20, 12], dtype=int64),
 array([12, 11], dtype=int64)]

In [176]:
test.pipeline_avgs()

array([ 3.5,  4.5,  5.5,  8. , 12.5, 17.5, 16. , 11.5])

In [177]:
text = """
        <option value="0">-- All --</option>
        <option value="10">10-2nd File LHR payout December .xlsx</option>
		<option value="100">100-KHI Fuel Payout April 26 - 28.xlsx</option>
		<option value="101">101-LHR Payout 24th - 30th April.xlsx</option>
		<option value="102">102-BulkUpload - 2023-05-04 Agencies and Reimbursements.xlsx</option>
		<option value="103">103-ISB Rental FTM of April.xlsx</option>
		<option value="104">104-ISB Payout 24th - 30th Apr.xlsx</option>
		<option value="105">105-LHR Toll Payout Apr.xlsx</option>
		<option value="106">106-LHR Rental Payout April .xlsx</option>
		<option value="11">11-Reattempt of Stuck Payments 9-Jan.xlsx</option>
		<option value="12">12-Karachi Fuel Payout.xlsx</option>
		<option value="13">13-Lahore Fuel payout 2nd - 8th Jan.xlsx</option>
		<option value="14">14-ISB Payout 2nd - 8th Jan .xlsx</option>
		<option value="15">15-Missing Fuel (Dec).xlsx</option>
		<option value="16">16-Karachi Fuel Payout 06-01-23 - 12-01-23.xlsx</option>
		<option value="17">17-ISB Payout 9th - 15th Jan.xlsx</option>
		<option value="18">18-LHR variable 9th - 15th Jan.xlsx</option>
		<option value="19">19-Karachi Monthly Rent 11 Dec - 10 Jan.xlsx</option>
		<option value="2">2-Testing File 2.xlsx</option>
		<option value="21">21-BulkUpload - 2023-01-19-Omar-Samsung.xlsx</option>
		<option value="22">22-BulkUpload - Loan Payoffs.xlsx</option>
		<option value="23">23-BulkUpload - 2023-01-24 - Agencies and Deposits.xlsx</option>
		<option value="24">24-Karachi Fuel Payout 13-01-23 - 19-01-23.xlsx</option>
		<option value="25">25-ISB payout 16 - 22 Jan.xlsx</option>
		<option value="26">26-LHR payout 16- 22 Jan.xlsx</option>
		<option value="27">27-Karachi Fuel Payout 20-01-23 - 27-01-23.xlsx</option>
		<option value="28">28-LHR variable 23rd - 29th Jan.xlsx</option>
		<option selected="selected" value="29">29-ISB Payout 23rd - 29th Jan.xlsx</option>
		<option value="3">3-Islamabad Payout 26t Dec - 1st Jan.xlsx</option>
		<option value="30">30-Karachi Fuel Payout 28-01-23 - 03-02-23.xlsx</option>
		<option value="31">31-LHR variable 30th Jan - 5th Feb.xlsx</option>
		<option value="32">32-ISB Payout 30th Jan - 5th Feb.xlsx</option>
		<option value="33">33-LHR Toll Payout Jan.xlsx</option>
		<option value="34">34-LHR JAN Rent Payout.xlsx</option>
		<option value="35">35-ISB payout 6th - 12th Feb.xlsx</option>
		<option value="36">36-LHR Payout 6th - 12th Feb.xlsx</option>
		<option value="37">37-Karachi Fuel Payout 04-02-23 - 09-02-23.xlsx</option>
		<option value="38">38-ISB payout 6th - 12th Feb (Reattempt).xlsx</option>
		<option value="39">39-Karachi Rent Payout - January 2023.xlsx</option>
		<option value="4">4-Lahore Variable Payout 26th Dec - 1st Jan.xlsx</option>
		<option value="40">40-Update January Rent Payout 2023.xlsx</option>
		<option value="43">43-Employee Reimbursements (21st Feb 2023).xlsx</option>
		<option value="44">44-LHR variable 13th - 19th Feb.xlsx</option>
		<option value="45">45-Fuel Payout ( 13-02-2023 - 18-02-2023.xlsx</option>
		<option value="46">46-ISB Payout 13th - 19th Feb.xlsx</option>
		<option value="48">48-BulkUpload - 2023-03-01 Agencies and Reimbursements.xlsx</option>
		<option value="49">49-Fuel 19-02-23 - 24-02-23.xlsx</option>
		<option value="5">5-Lahore Rent Payout FTM of Dec.xlsx</option>
		<option value="50">50-LHR variable Payout 20th - 26th Feb.xlsx</option>
		<option value="51">51-ISB Payout 20th - 26th Feb.xlsx</option>
		<option value="52">52-Lahore FEB Rental.xlsx</option>
		<option value="53">53-Lahore Feb Tolls.xlsx</option>
		<option value="54">54-27-02-2023 - 03-02-2023 fuel payout.xlsx</option>
		<option value="55">55-LHR Variable 27th Feb - 5th Mar.xlsx</option>
		<option value="56">56-BulkUpload - 2023-03-09 Agencies and Reimbursements.xlsx</option>
		<option value="57">57-ISB Payout 27th Feb - 5th Mar.xlsx</option>
		<option value="58">58-27-02-23 -03-03-23.xlsx</option>
		<option value="59">59-Feb - Rent Karachi 2023.xlsx</option>
		<option value="60">60-Fuel  06-03-23 - 10-03 -23.xlsx</option>
		<option value="61">61-LHR Variable Payout 6th - 12th Mar.xlsx</option>
		<option value="62">62-ISB Payout 6 - 12 Mar.xlsx</option>
		<option value="64">64-Feb 10-Mar 10 Karachi Rent.xlsx</option>
		<option value="65">65-Marach 06 -10 Karachi Fuel.xlsx</option>
		<option value="66">66-Fuel Payment March.xlsx</option>
		<option value="67">67-ISB payout 13th - 19th March.xlsx</option>
		<option value="68">68-LHR payout 13th - 19th March.xlsx</option>
		<option value="69">69-Fuel Payment March 3.xlsx</option>
		<option value="7">7-Toll Payout LHR FTM of Dec.xlsx</option>
		<option value="70">70-ISB Payout 20th - 26th Mar.xlsx</option>
		<option value="71">71-LHR Payout 20th-26th Mar.xlsx</option>
		<option value="72">72-Fuel March 4.xlsx</option>
		<option value="73">73-LHR payout 27th Mar - 2nd Apr.xlsx</option>
		<option value="74">74-ISB Rent + Fuel (27Mar-2Apr).xlsx</option>
		<option value="75">75-LHR Rent Payout Mar.xlsx</option>
		<option value="76">76-LHR Toll Payout Mar.xlsx</option>
		<option value="77">77-BulkUpload - 2023-04-10 Agencies and Reimbursements.xlsx</option>
		<option value="78">78-Fuel Payout Apirl 03 - 07 .xlsx</option>
		<option value="79">79-ISB payout 3rd - 9th April .xlsx</option>
		<option value="8">8-LHR Rent Payout FTM of Dec.xlsx</option>
		<option value="80">80-LHR Payout 3rd - 9th Apr.xlsx</option>
		<option value="81">81-LHR Rental till 9th April.xlsx</option>
		<option value="82">82-LHR Tolls Till 9th April.xlsx</option>
		<option value="83">83-March Rent Retail.xlsx</option>
		<option value="84">84-Fuel Payout April 10 - 14.xlsx</option>
		<option value="85">85-ISB payout 10th - 16th April.xlsx</option>
		<option value="86">86-LHR Eid Captain Bonus.xlsx</option>
		<option value="87">87-LHR captain eid bonus 2.xlsx</option>
		<option value="88">88-Captain Bonus.xlsx</option>
		<option value="89">89-LHR Variable 10th - 16th April.xlsx</option>
		<option value="9">9-LHR Toll Payout FTM of Dec.xlsx</option>
		<option value="90">90-Eid Bonus.xlsx</option>
		<option value="91">91-ISB Eid Captain Bonus.xlsx</option>
		<option value="92">92-ISB Eid Bonus Reattempt 1.xlsx</option>
		<option value="93">93-BulkUpload - Employee Eidi.xlsx</option>
		<option value="94">94-LHR Eid Bonus Reattempt 1.xlsx</option>
		<option value="95">95-LHR Eid Bonus Reattempt 2.xlsx</option>
		<option value="96">96-LHR Eid Bonus Reattempt 3.xlsx</option>
		<option value="97">97-LHR Payout 17th - 23rd April.xlsx</option>
		<option value="98">98-ISB payout 17th - 23rd April.xlsx</option>
		<option value="99">99-Fuel Payout April 17 - 20.xlsx</option>
		<option value="SI">SI</option>
"""

text.split(".xlsx")

text_list = []

for i in text.split('.xlsx'):
    text_list.append(i.split(">")[2])

text_list

import pandas as pd

pd.DataFrame(text_list[1:]).to_csv(r'text_list.csv')

In [178]:
from InvestopediaApi import ita

In [179]:
import config

client = ita.Account(config.email, config.password)

In [ ]:
import mechanicalsoup
from enum import Enum
from collections import namedtuple
from bs4 import BeautifulSoup
import re

class Account:
    BASE_URL = 'http://www.investopedia.com'

    def __init__(self, email, password):
        """
        Logs a user into Investopedia's trading simulator,
        given a *username* and *password*.
        """

        self.br = br = mechanicalsoup.Browser()
        login_page = self.fetch("/accounts/login.aspx?returnurl=http://www.investopedia.com/simulator/")

        # you have to select the form before you can input information to it
        # the login form used to be at nr=2, now it's at nr=0
        login_form = login_page.soup.select("form#account-api-form")[0]
        login_form.select("#edit-email")[0]["value"] = email
        login_form.select("#edit-password")[0]["value"] = password
        br.submit(login_form, login_page.url)

    def fetch(self, url):
        url = '%s%s' % (self.BASE_URL, url)
        return self.br.get(url)


In [ ]:
print(mechanicalsoup.Browser())

In [ ]:
url = 'https://www.investopedia.com/auth/realms/investopedia/protocol/openid-connect/auth?state=0e46b55bdc7794591c4b092f8e4d14d4&scope=email&response_type=code&approval_prompt=auto&redirect_uri=https://www.investopedia.com/simulator/home.aspx&client_id=inv-simulator-conf'

mechanicalsoup.Browser().get(url)

<Response [405]>

In [ ]:
import requests

requests.get(url)

<Response [405]>

In [ ]:
x = Account(config.email, config.password)

AttributeError: 'NoneType' object has no attribute 'select'